name: Deploy Hostinger to FTP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar FTP y subir archivos
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v3
        with:
          ftp-server: ftp://185.173.111.249
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /dist/.
          remote-dir: /public_html  # Ruta en tu servidor FTP
          exclude: .git* 
