name: Deploy Hostinger to FTP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar FTP y subir archivos
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 185.173.111.249
          username: u553004748.membranas202.com.ar # Cambiado de ftp-username a username
          password: DeployFTP*2024 # Cambiado de ftp-password a password
          local-dir: ./dist/ # Cambia esto si tu directorio es diferente
          server-dir: ./ # Cambiado de remote-dir a server-dir
          log-level: verbose # Opcional para ver más detalles
